name: Task2

on: [push,pull_request]

jobs:
  run-script:
    runs-on: ubuntu-latest

  steps:
    - name: run the scripts
      run: |
        chmod +x dataset1/task2a.sh
        chmod +x dataset1/task2b.sh
        chmod +x dataset1/task2c.sh
        ./task2.sh