name: Task1 Run Script

on: [push,pull_request]

jobs:
  run-script:
    runs-on: ubuntu-latest
    
  steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: Run the script
      run:  |
        chmod +x task1.sh
        ./task1.sh